### ISSUE TITLE
Encourages swallowing errors.

### ISSUE THREAD

**Issue by voltrevo** [zoubin/array-promise-filter#1]
If someone really wants to filter based on promise errors, they should really be explicitly catching and returning a boolean somewhere. It's completely appropriate that if your filter function throws, the overall filter should throw too, not exclude the elements that threw.

I mean, you're free to do what you want of course, but I came across this library because I wanted a good promise based filter. And there's no way I would use something like this. It's extremely important to me that my errors propagate.

**Comment by zoubin** [comment]
@voltrevo I agree with you.
Perhaps you can try [array-async-filter](https://github.com/zoubin/array-async-filter). 
It propagates errors.

**Comment by zoubin** [comment]
You can handle errors now in 1.0.0

**Comment by voltrevo** [comment]
:+1:

I ended up using this though:

``` js
'use strict';

module.exports = function(arr, filterFn) {
  return Promise.all(arr.map(function(el) {
    return Promise.resolve(el).then(function(elVal) {
      return Promise.all([filterFn(elVal), elVal]);
    });
  })).then(function(pairs) {
    return pairs.filter(function(pair) {
      return pair[0];
    }).map(function(pair) {
      return pair[1];
    });
  });
};
```

https://github.com/voltrevo/abstract-fs/blob/327626c2aaeac496cfaff719d2ddd82821c6a0f4/lib/util/promiseFilter.js
